### ISSUE TITLE
Feature request: window info, watch, actions

### ISSUE THREAD

**Issue by IGalat** [Zuzu-Typ/winput#7]
Hi @Zuzu-Typ ,

This is probably out of scope for winput, but: window tracking and info!
[Here's the example](https://gist.github.com/keturn/6695625) that logs window changes. Would be nice to hook window much like keyboard and mouse now and track the changes.
With it also functions to get all opened windows, currently active window.

**Comment by Zuzu-Typ** [comment]
Hi there @IGalat 

Indeed, I fear this would be out of scope for winput.
