### ISSUE TITLE
[Not a] Bug: set_mouse_pos wrong coords

### ISSUE THREAD

**Issue by IGalat** [Zuzu-Typ/winput#8]
Hi @Zuzu-Typ ,

I'm trying to use set_mouse_pos and getting a really weird bug.
Supplying it 0 0 works well, but for 100 100 it moves the mouse to 125 125. Same applies to any coords, x=1000 moves it to 1250, 500 to 625 etc.

I see there's not much going on in winput itself, but bug exists and is easily reproducible for me (tried rebooting and shutting down everything else).

Debug confirms that coords that go into winput function are the ones I expect, not 25% higher. I confirmed coords wih ahk tooltip, and also visually - I know x and y max, I see cursor going into the corner at coords less than max, and trying to move to center results in mouse being off center.

**Comment by Zuzu-Typ** [comment]
Hi @IGalat 

the reason for that is simple. It's a feature of Windows called cursor acceleration. You can turn it off in the Windows mouse settings.

**Comment by Zuzu-Typ** [comment]
Oops, never mind. I was thinking about `move_mouse` 🤦🏻‍♂️

This has to do with DPI values (probably). See https://github.com/Zuzu-Typ/winput#dpi-awareness for more info

**Comment by IGalat** [comment]
Oh that's correct, this resolves the issue. Thanks.
